In [1]:
#Dependencies
import pandas as pd
from sportsreference.nba.teams import Teams

In [2]:
#Importing stats from the 2019-2020 NBA Season *A full regular season was not played due to Covid-19*
teams = Teams("2020")

stats_19_20 = teams.dataframes
stats_19_20.head()

,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,...,rank,steals,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals
DAL,DAL,1849,363,2729,6772,0.461,3124,1787,0.779,1392,...,1,460,3095,0.367,1136,3520,953,3677,0.541,1988
MIL,MIL,1889,429,3083,6638,0.476,3160,1800,0.742,1336,...,2,526,2840,0.355,1007,3774,1102,3798,0.567,2153
POR,POR,1525,451,2599,6749,0.463,3122,1632,0.804,1312,...,3,465,2525,0.377,952,3353,946,4224,0.514,2170
HOU,HOU,1557,371,2484,6512,0.451,2936,1876,0.791,1484,...,4,627,3261,0.345,1126,3188,1057,3251,0.557,1810
LAC,LAC,1708,338,2664,6425,0.466,2992,1894,0.791,1498,...,5,511,2410,0.371,895,3431,1051,4015,0.522,2097

In [3]:
#subsetting for three point values
#
threes_20 = stats_19_20[['three_point_field_goal_attempts', 'three_point_field_goal_percentage',
       'three_point_field_goals', "games_played"]].copy()
threes_20

,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,games_played
DAL,3095,0.367,1136,75
MIL,2840,0.355,1007,73
POR,2525,0.377,952,74
HOU,3261,0.345,1126,72
LAC,2410,0.371,895,72
NOP,2656,0.370,982,72
PHO,2320,0.358,831,73
WAS,2345,0.368,864,72
MEM,2297,0.347,798,73
BOS,2487,0.364,905,72
MIA,2584,0.379,979,73
DEN,2234,0.359,801,73
TOR,2663,0.374,995,72
SAS,2021,0.376,760,71
PHI,2307,0.368,848,73
LAL,2242,0.349,782,71
BRK,2746,0.343,941,72
UTA,2537,0.380,963,72
IND,2046,0.363,743,73
OKC,2171,0.355,770,72
SAC,2511,0.364,914,72
ORL,2354,0.343,807,73
ATL,2416,0.333,805,67
MIN,2540,0.336,853,64
DET,2157,0.367,791,66
NYK,1872,0.337,631,66
CLE,2070,0.351,727,65
CHI,2282,0.348,793,65
GSW,2032,0.334,678,65
CHO,2231,0.352,785,65

In [4]:
#creating a new column for avg attempts/makes per game
threes_20["three_point_field_goal_attempts_per_game"] = round(threes_20["three_point_field_goal_attempts"] / threes_20["games_played"],2)
threes_20["three_point_field_goals_per_game"] = round(threes_20["three_point_field_goals"] / threes_20["games_played"],2)

threes_20

,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,games_played,three_point_field_goal_attempts_per_game,three_point_field_goals_per_game
DAL,3095,0.367,1136,75,41.27,15.15
MIL,2840,0.355,1007,73,38.90,13.79
POR,2525,0.377,952,74,34.12,12.86
HOU,3261,0.345,1126,72,45.29,15.64
LAC,2410,0.371,895,72,33.47,12.43
NOP,2656,0.370,982,72,36.89,13.64
PHO,2320,0.358,831,73,31.78,11.38
WAS,2345,0.368,864,72,32.57,12.00
MEM,2297,0.347,798,73,31.47,10.93
BOS,2487,0.364,905,72,34.54,12.57
MIA,2584,0.379,979,73,35.40,13.41
DEN,2234,0.359,801,73,30.60,10.97
TOR,2663,0.374,995,72,36.99,13.82
SAS,2021,0.376,760,71,28.46,10.70
PHI,2307,0.368,848,73,31.60,11.62
LAL,2242,0.349,782,71,31.58,11.01
BRK,2746,0.343,941,72,38.14,13.07
UTA,2537,0.380,963,72,35.24,13.38
IND,2046,0.363,743,73,28.03,10.18
OKC,2171,0.355,770,72,30.15,10.69
SAC,2511,0.364,914,72,34.88,12.69
ORL,2354,0.343,807,73,32.25,11.05
ATL,2416,0.333,805,67,36.06,12.01
MIN,2540,0.336,853,64,39.69,13.33
DET,2157,0.367,791,66,32.68,11.98
NYK,1872,0.337,631,66,28.36,9.56
CLE,2070,0.351,727,65,31.85,11.18
CHI,2282,0.348,793,65,35.11,12.20
GSW,2032,0.334,678,65,31.26,10.43
CHO,2231,0.352,785,65,34.32,12.08

In [5]:
#summary statistics for the 2019-2020 season for 3s
threes_20.describe()

,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,games_played,three_point_field_goal_attempts_per_game,three_point_field_goals_per_game
count,30.000000,30.000000,30.000000,30.000000,30.000000,30.000000
mean,2408.400000,0.357767,862.066667,70.600000,34.098333,12.191667
std,311.154979,0.014127,120.013486,3.328042,3.929254,1.441759
min,1872.000000,0.333000,631.000000,64.000000,28.030000,9.560000
25%,2231.750000,0.347250,786.500000,68.000000,31.585000,11.020000
50%,2349.500000,0.358500,839.500000,72.000000,33.795000,12.045000
75%,2539.250000,0.368000,949.250000,73.000000,35.895000,13.265000
max,3261.000000,0.380000,1136.000000,75.000000,45.290000,15.640000

In [6]:
#nba data over the last 10 years
year = 2010

for i in range(10):
    year = str(year)
    new_year = Teams(year)
    new_year = new_year.dataframes
    new_year["year"] = year

    if year == "2010":
        stats_10s = new_year
    else:
        stats_10s = pd.concat([stats_10s,new_year])
        
    year = int(year)
    year += 1

stats_10s.head()

,abbreviation,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,...,steals,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals,year
PHO,PHO,1912,418,2616,6788,0.492,3339,2117,0.770,1631,...,479,1770,0.412,730,3526,1210,5018,0.520,2609,2010
GSW,GSW,1839,340,2397,7094,0.469,3329,2085,0.782,1631,...,761,1687,0.375,633,3150,1204,5407,0.499,2696,2010
DEN,DEN,1719,417,2505,6678,0.468,3124,2508,0.772,1937,...,683,1517,0.359,544,3394,1136,5161,0.500,2580,2010
UTA,UTA,2187,400,2588,6575,0.491,3227,2233,0.741,1654,...,675,1207,0.364,439,3460,1246,5368,0.519,2788,2010
TOR,TOR,1804,384,2507,6631,0.482,3199,2118,0.764,1618,...,469,1397,0.371,518,3313,1100,5234,0.512,2681,2010

In [8]:
#data summary
stats_10s.describe()

,assists,blocks,defensive_rebounds,field_goal_attempts,field_goal_percentage,field_goals,free_throw_attempts,free_throw_percentage,free_throws,games_played,...,rank,steals,three_point_field_goal_attempts,three_point_field_goal_percentage,three_point_field_goals,total_rebounds,turnovers,two_point_field_goal_attempts,two_point_field_goal_percentage,two_point_field_goals
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,...,300.000000,300.00000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.00000,300.000000
mean,1791.880000,393.016667,2595.863333,6742.286667,0.455493,3071.810000,1859.843333,0.760053,1412.996667,80.393333,...,15.500000,613.67000,1860.843333,0.354887,662.736667,3453.530000,1151.533333,4881.443333,0.49420,2409.073333
std,212.824528,63.029454,247.250049,525.457009,0.015521,268.489022,230.314759,0.029504,178.639779,4.806485,...,8.669903,77.24734,519.024057,0.018467,193.967054,279.316777,106.862595,446.588698,0.02318,210.758722
min,1224.000000,195.000000,1879.000000,5086.000000,0.408000,2193.000000,1198.000000,0.660000,889.000000,66.000000,...,1.000000,390.00000,777.000000,0.295000,259.000000,2560.000000,738.000000,3377.000000,0.43900,1605.000000
25%,1689.000000,347.000000,2477.000000,6638.000000,0.444000,3000.250000,1715.750000,0.745000,1311.250000,82.000000,...,8.000000,564.00000,1462.750000,0.343000,507.750000,3355.000000,1093.250000,4574.500000,0.47875,2303.000000
50%,1795.500000,387.500000,2628.000000,6844.500000,0.454000,3124.500000,1870.000000,0.761000,1423.000000,82.000000,...,15.500000,615.00000,1838.500000,0.354000,660.000000,3507.000000,1152.500000,4939.500000,0.49200,2447.000000
75%,1917.000000,436.000000,2774.500000,7051.500000,0.465250,3212.250000,2000.250000,0.780000,1520.000000,82.000000,...,23.000000,670.25000,2197.500000,0.367000,806.250000,3629.750000,1223.000000,5200.750000,0.50825,2540.250000
max,2491.000000,624.000000,3316.000000,7706.000000,0.503000,3612.000000,2549.000000,0.828000,1977.000000,82.000000,...,30.000000,821.00000,3721.000000,0.416000,1323.000000,4078.000000,1453.000000,5875.000000,0.56500,2891.000000

In [9]:
#writing to csv
stats_10s.to_csv("../data/stats_10s.csv")